version: '3'
services:
  frontend:
    build:
      context: ./calc-app
      dockerfile: Dockerfile
    ports:
      - 3003:3000
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3004:3000
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27018:27017
    networks:
      - app-network
    volumes:
      - ./data:/data/db
    command: --replSet rs0

networks:
  app-network:
